Toniof 352 support typespecifiers
dcs4cop/xcube-cci pull request #19
Opened 2020-11-11 08:45 UTC by TonioF

Solves https://github.com/dcs4cop/xcube-cci/issues/18 . Relies on https://github.com/dcs4cop/xcube/pull/359 .

2020-11-11 16:04 UTC, forman requested changes
Good, just a tiny suggestion for `environment.yml`!

2020-11-11 16:04 UTC, forman commented on environment.yml
> +  - xcube
This file can only be used with "conda env create" or "conda env update" and then it will require xcube >= 0.6.

2020-11-12 07:54 UTC, TonioF commented on environment.yml
> +  - xcube
Agreed and Done.

2020-11-12 11:18 UTC, pont-us requested changes
Requested changes are suggestions only. Feel free to ignore if you disagree.

2020-11-12 13:29 UTC, TonioF commented on test/test_dataaccess.py
> +        self.assertEqual(('dataset', 'dataset[cube]'), type_specifiers_for_data)
As the documentation says that the first entry of the tuple represents the default type, I want to to leave it like this. We might want to think this through again when the store also supports geodataframes.

2020-11-12 13:33 UTC, TonioF commented on test/test_dataaccess.py
> +                             'esacci.AEROSOL.day.L3.AAI.multi-sensor.multi-platform.MSAAI.1-7.r1', 'dataset'))
The documentation says nothing about the order, but 'd still like to keep this to indicate that the first one is the default.

2020-11-12 13:34 UTC, TonioF commented on test/test_dataaccess.py
> +        self.assertTrue('sample_standard_deviation' in dataset.variables)
Yes, you're right. I don't know why I did it like this.

2020-11-12 14:05 UTC, merged